# === to rebuild containers ===
# docker-compose down
# docker-compose up -d --build --force-recreate

version: '3'
services:
  ultrasound-client:
    container_name: ultrasound-frontend
    image: ultrasound-frontend-img
#    hostname:
#    build: ./frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - '.:/app'
      - '/app/node_modules'



#version: "3.8"
#services:
#  mongodb:
#    image: mongo
#    container_name: mongodb-dev
#    ports:
#      - 27017:27017
#    volumes:
#      - data:/data
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=rootuser
#      - MONGO_INITDB_ROOT_PASSWORD=rootpass
#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express-dev
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
#      - ME_CONFIG_MONGODB_SERVER=mongodb
#volumes:
#  data: {}
